version: "3"
services:
  server:
    image: wilsonzhong/yueba_server:latest
    container_name: yueba_server
    environment:
      HOST: 172.17.0.1
    depends_on:
      - "database"
    ports:
      - 8080:8080
  database:
    image: wilsonzhong/yueba_mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: YueBa
    container_name: yueba_mysql
    ports:
      - 3306:3306
    volumes:
      - ~/mysql:/var/lib/mysql