version: "3"
services:
  server:
    image: wilsonzhong/yueba_server:latest
    container_name: yueba_server
    environment:
      HOST: mysql
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
  mysql:
    image: wilsonzhong/yueba_mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: YueBa
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/mysql:/var/lib/mysql