version: "1"
services:
  server:
    image: wilsonzhong/yueba_server:latest
    container_name: yueba_server
    ports:
      - 8080:8080
    volumes:
      - ~/data/public:/app/public
      - ~/data/YueBa.sqlite:/app/YueBa.sqlite
